### ISSUE TITLE
JSON schema: time_zone_name has very narrow definition

### ISSUE THREAD

**Issue by rixx** [voc/schedule#108]
In the JSON schema at https://github.com/voc/schedule/blob/master/validator/json/schema.json, the time zone name is defined as `"^[A-Z][a-z+]/[A-Z][a-z+]$"`. However, this definition does not allow the name "UTC", which is commonly used and understood in time zone names. (pretalx uses UTC in some cases.)

If the definition was something less restrictive like `"[A-Z][A-Za-z/+]"`, we could start validating the JSON export generated by pretalx (cf pretalx/pretalx#1338) against this JSON schema, which would be pretty cool.

**Comment by saerdnaer** [comment]
Looking at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones I would really prefer if the organisers would choose a specific time zone using the `<Continent>/<City>` pattern, but we can add UTC to the list.
