### ISSUE TITLE
Merged <person>-Element does not contain a string

### ISSUE THREAD

**Issue by MaZderMind** [voc/schedule#11]
Comparing the `everything.schedule.xml` with `https://events.ccc.de/congress/2014/Fahrplan/schedule.xml` it turns out, that in the merged version the `<people>` elements now contains sub-elements, that aren't present in the original document:

everything.schedule.xml
--------------------------------
````
<persons>
  <person id="0">
    <full_public_name>Willscott</full_public_name>
    <url>
      https://events.ccc.de/congress/2015/wiki/User:Willscott
    </url>
  </person>
</persons>
````

2014/Fahrplan/schedule.xml
--------------------------------
````
<persons>
  <person id="1544">erdgeist</person>
  <person id="3874">Geraldine de Bastion</person>
</persons>
````

I'd suggest to move the extra attributes into xml-attributes while keeping the `full_public_name` as Text-Content

**Comment by saerdnaer** [comment]
Interesting that the validator did't list this issue. Maybe we also have to fix the DTD.

**Comment by saerdnaer** [comment]
@manno what kind of attribute name should I use for the userpage url? `href`? Or is it a better Idea to add an addional `<link>` element?
```
<persons>
  <person id="0" href="https://events.ccc.de/congress/2015/wiki/User:Willscott">Willscott</person>
</persons>
```

**Comment by MaZderMind** [comment]
Adding subelements to elements that are supposed to contain only CDATA is changing the semantic, thus I would favor using an attribute over another element. I don't care what the attribute is named ;)
