### ISSUE TITLE
<event>s grouped under a single <room>-Element

### ISSUE THREAD

**Issue by MaZderMind** [voc/schedule#12]
Comparing the `everything.schedule.xml` with `https://events.ccc.de/congress/2014/Fahrplan/schedule.xml` it turns out, that in the merged version the `<event>`-Tags of a day are now grouped under a single `<room>` Element who's name does not correspond to the `<event>`s `room="…"` attribute.

everything.schedule.xml
--------------------------------
````
<room name="HardwareHackingArea">
  <event id="7550" guid="654331ae-1710-42e5-bdf4-65a03a80c614">
    …
    <room>Hall 1</room>
  </event>
  …
  <event id="7324" guid="d66db4df-49ed-4c9f-ada3-289d16786c8e">
    …
    <room>Hall 2</room>
  </event>
  …
</room>
````

2014/Fahrplan/schedule.xml
--------------------------------
````
<room name="Saal 1">
  <event guid="29aecfd7-2e44-4f49-ab86-29b5e0877325" id="6561">
    …
    <room>Saal 1</room>
  </event>
</room>
<room name="Saal 2">
  <event guid="mzNAGavKy2KOcwOjGqC8pw" id="6443">
    …
    <room>Saal 2</room>
  </event>
  …
</room>
````

**Comment by saerdnaer** [comment]
I will regenerated example files tomorrow, when the other issue is also fixed.
