### ISSUE TITLE
JSON schema: Missing definition `/definitions/Answers`

### ISSUE THREAD

**Issue by Kunsi** [voc/schedule#145]
https://github.com/voc/schedule/blob/master/validator/json/schema.json#L312 refers to `https://c3voc.de/schedule/submission#/definitions/Answers` which looks wrong, but the `Answers` definition is missing from the schema altogether, which leads to validation errors.

**Comment by saerdnaer** [comment]
Hmm, it should refer to https://github.com/voc/schedule/blob/master/validator/submission-json/schema.json#L267-L342 which is different to https://github.com/voc/schedule/blob/master/validator/submission-json/submission.json as I now realise... Its probably the best to move the answers defintion there...

**Comment by rixx** [comment]
So exporters should now inline the full question rather than just including the question ID?

(FWIW: pretalx will at some point rename "question/answer" to "custom field", as that makes a lot more sense imo, and people regularly get confused by the current wording.)

**Comment by rixx** [comment]
Notably, the schema.json [does NOT include a type for speaker answers](https://github.com/voc/schedule/blob/master/validator/json/schema.json#L425).

**Comment by saerdnaer** [comment]
> (FWIW: pretalx will at some point rename "question/answer" to "custom field", as that makes a lot more sense imo, and people regularly get confused by the current wording.)
Thats a good idea! So lets drop the answer field for now from the schema definition and let's revisit it as form a custom field, which could include a `key` additional to the `question` – I also saw some interesting ideas at custom field implementation in pretix...
