### ISSUE TITLE
validator is not warning on empty guids

### ISSUE THREAD

**Issue by derpeter** [voc/schedule#23]

**Comment by Florob** [comment]
Is the problem solely with empty guid attributes, or should the attribute be required (it is currently optional).

**Comment by a-tze** [comment]
The attribute is required, must not be emtpy and in an ideal world it is checked for uniqueness

**Comment by a-tze** [comment]
could be fixed in a95e372bd388cc97a3774291f18ad47d12695c83

**Comment by Florob** [comment]
The current XSD still allows one empty, as well as multiple absent guid attributes. I have a patch to fix this, as well as check for the attribute containing a valid UUID. Unless there is any reason we ever wouldn't want to require this is a UUID I'll commit it later.

**Comment by saerdnaer** [comment]
@Florob I think we should always require a UUID. Can you commit your patch?
