### ISSUE TITLE
Different workshops with same id 

### ISSUE THREAD

**Issue by johnjohndoe** [voc/schedule#31]
I noticed that the current version of the 34c3 _everything.schedule.xml_ contains a workshop which uses the same id as another workshop.

``` xml
<event guid="7b0f781c-32ec-4c4d-9e02-7e5b9177aef4" id="1120">
    <logo/>
    <date>2017-12-30T14:00:00+01:00</date>
    <start>14:00</start>
    <duration>0:30</duration>
    <room>Lecture room 12</room>
    <slug/>
    <title>Sharding and Proof of Stake - Vlad Zamfir</title>
    <subtitle/>
    <track>self organized sessions</track>
    <type>talk</type>
    <language>en</language>
    <abstract/>
    <description>Vlad Zamfir is one of the Lead architects of Proof of Stake and Sharding for Ethereum. He has deep insights into these topics and many others at the philosophical and game theoretical heart of the blockchain world, plus he sounds really smart when he talks ;-)</description>
    <persons/>
    <links>
        <link>http://www.ethereum.org</link>
        <link>https://events.ccc.de/congress/2017/wiki/index.php/Session:Sharding_and_Proof_of_Stake_-_Vlad_Zamfir</link>
    </links>
</event>
```

and 

``` xml
<event guid="7b0f781c-32ec-4c4d-9e02-7e5b9177aef4" id="1120">
    <logo/>
    <date>2017-12-30T16:05:00+01:00</date>
    <start>16:05</start>
    <duration>0:55</duration>
    <room>Chaos West Stage</room>
    <slug/>
    <title>Ethereum AMA</title>
    <subtitle/>
    <track>self organized sessions</track>
    <type>talk</type>
    <language>en</language>
    <abstract/>
    <description>There are several Ethereum Superstars at this conference, they are congregating on the Chaos West Stage to answer all of your questions about the decentralized world computer. :-D</description>
    <persons/>
    <links>
        <link>http://www.ethereum.org</link>
        <link>https://events.ccc.de/congress/2017/wiki/index.php/Session:Ethereum_AMA</link>
    </links>
</event>
```

Here is the full XML file for your reference (renamed to txt so I can upload here): [everything.schedule.xml.txt](https://github.com/voc/schedule/files/1594375/everything.schedule.xml.txt)

**Comment by saerdnaer** [comment]
This year, the guid's were generated by mediawiki. The user 'Griff' probably copy&pasted a page manually, without modifying the random guid.

* https://events.ccc.de/congress/2017/wiki/index.php?title=Session:Sharding_and_Proof_of_Stake_-_Vlad_Zamfir&action=history
* https://events.ccc.de/congress/2017/wiki/index.php?title=Session:Ethereum_AMA&action=history

I would opt for adding a warning message, for this case – when we are still using the wiki next year.

**Comment by johnjohndoe** [comment]
Please **reference the script here** where you would add such as warning message.

**Comment by saerdnaer** [comment]
Hmm, there are multiple options: 

The easiest is probably after https://github.com/voc/schedule/blob/34C3/wiki2schedule_34C3.py#L288. You require a list with all GUID's which have been used at that point. 

However theoretically this could still lead to duplicated guid's as the other sources beside the wiki are not checked.  The resolve this, one could add a validation step checking the guids, which the xsd already does:
https://github.com/voc/schedule/blob/master/validator/xsd/schedule.xml.xsd#L24-L27

The last option is to migrate the wiki2schedule script to use the https://github.com/voc/voctosched classes which already uses the xsd for validation.
