### ISSUE TITLE
Format of <links> element changed from 34c3 to 35c3

### ISSUE THREAD

**Issue by johnjohndoe** [voc/schedule#34]
I noticed that the format of the `<links>` element has changed in `*schedule.xml` from 34c3 to 35c3.
Here is a random example from each file:

[Example from 34C3 everything.schedule.xml](https://github.com/voc/34C3_schedule/blob/a206f5f04650b87a5f9364d10df6004ca852a9d9/everything.schedule.xml#L112):

``` xml
<links>
  <link href="https://www.youtube.com/watch?v=pUEp3uWAWqY">Waffeln an der Elektrotankstelle backen</link>
  <link href="https://evsim.gonium.net/">EVSim: Ein einfacher Elektroauto-Simulator</link>
</links>
```

[Example from 35C3 everything.schedule.xml]( https://github.com/voc/35C3_schedule/blob/2bdb57b0c4d9facde49ae381166d65db738264ff/everything.schedule.xml#L956):

``` xml
<links>
  <link>
    <url>https://edri.org/press-release-eu-parliament-flip-flops-backwards-on-copyright/</url>
    <title>EDRi's analysis on the adoption of upload filters</title>
  </link>
  <link>
    <url>https://www.eff.org/deeplinks/2018/09/today-europe-lost-internet-now-we-fight-back</url>
    <title>EFF analysis of upload filters in the EU</title>
  </link>
</links>
```

The issue I have with this is that it **breaks the parser** in the [EventFahrplan](https://github.com/EventFahrplan/EventFahrplan) app. Is this change intentional? Can you provide the XML in the former format?

**Comment by saerdnaer** [comment]
Should be possible – I simply have to revert https://github.com/voc/schedule/commit/30d7dd89e2e54f9b39831d1a9ca84f96cbb67ae3 and add an `parent != 'event'` check. :-)
