### ISSUE TITLE
Add time_zone_name element

### ISSUE THREAD

**Issue by johnjohndoe** [voc/schedule#69]
# Proposal
- I hereby propose to add a new `time_zone_name` element. The element might be a child of the `conference` element.
- It should contain the descriptive long textual form of a standardized time zone, e.g. `Europe/Berlin`.

# Use case
- The [36C3 Schedule app](https://github.com/EventFahrplan/EventFahrplan) allows users to share a session to social media. Shared is the title, date and where takes place. The date should contain time zone information because people this message is shared with are located in a different time zone than the event takes place. A suggested by @a-tze it is more user-friendly to append the long textual representation of the time zone, e.g. `Europe/Berlin` instead of the too technical short form, e.g. `GMT+02:00`.

# Affected
- [frab](https://github.com/frab/frab)
- [Pretalx](https://github.com/pretalx/pretalx)

# Related
- [EventFahrplan, issue #296, Append time zone offset when sharing a session as plain text](https://github.com/EventFahrplan/EventFahrplan/pull/296)
- [voc/schedule PR #70: add optional time_zone_name element to schedule XML schema](https://github.com/voc/schedule/issues/70)
- [Wikipedia, List of tz database time zones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
- [IANA, Time Zone Database](https://www.iana.org/time-zones)

---

/cc @saerdnaer, @manno, @rixx, @saerdnaer, @ideadapt

**Comment by rixx** [comment]
Speaking for pretalx, adding this element wouldn't pose any problem, I'm +1 on doing it. Let's add it as an optional element to the schema so that older and newer `schedule.xml` versions both navigate, and all should be good?

**Comment by a-tze** [comment]
I have created PR #70 for this, please feel free to comment, especially @rixx @manno @saerdnaer

**Comment by saerdnaer** [comment]
Merged https://github.com/voc/schedule/pull/70, closing this

**Comment by johnjohndoe** [comment]
For the record: :heavy_check_mark: the _time zone name_ is used if available in the different publications of the [EventFahrplan](https://github.com/EventFahrplan/EventFahrplan) project namingly _36C3 Schedule_, _rC3 2020 Schedule_, _FOSDEM 2021 Schedule_ and more to come. Thank you for adding this feature.
