### ISSUE TITLE
Schemas validity error : Element 'generator': This element is not expected. Expected is ( day ).

### ISSUE THREAD

**Issue by johnjohndoe** [voc/schedule#86]
When I run `schedule_divoc.py` then the following validation error is output:

> Exporting... everything.schedule.xml:3061: element generator: Schemas validity error : Element 'generator': This element is not expected. Expected is ( day ).
> everything.schedule.xml fails to validate

Tested with 8373cfce1b097f24057afc6d4cbe17695ab47598. :sos: Help is welcome here.

**Comment by johnjohndoe** [comment]
I believe the attribute is just in the wrong order. Am I right?

**Comment by Florob** [comment]
Yes, as is `<generator/>` needs to be the first child element of `<schedule/>`.
