### ISSUE TITLE
Missing information in diff between frab schedule.xml and schedule.json

### ISSUE THREAD

**Issue by saerdnaer** [voc/schedule#9]
Missing in schedule.json
* conference - acronym
* event - recording - licence

MIssing in schedule.xml
* event - logo

**Comment by saerdnaer** [comment]
@manno Does it make sense to fix this issues in frab?

**Comment by manno** [comment]
Yes, sounds good.

**Comment by saerdnaer** [comment]
was fixed with https://github.com/frab/frab/commit/52a3d25f1f991530e3f68a0125245dacf3332fe1
